Removed joml dependency
Removed joml dependency, unused for now and creates an error when
building the app:
com.android.build.api.transform.TransformException:
com.android.ide.common.process.ProcessException:
java.util.concurrent.ExecutionException: com.android.dex.DexException:
Multiple dex files define Lorg/joml/AxisAngle4d
The lib might already be imported by the gearvrf.